#!/bin/bash

choice="$1"
shift
files=$(echo "$@" | xargs)
case "$choice" in
	"-c") 	notify-send "$files"
		if arch=$(echo | dmenu --font "FiraCode Nerd Font-14"); then
			command="apack $arch $files"
			eval "$command"
		fi
		;;
	"-e")	aunpack "$files"
		;;
	*) 	echo -e "USAGE: compression: archiver -c <file>\nextract: archiver -e <file>\nEnter archive name (example.zip) in dmenu prompt.";;
esac
