#!/bin/bash

if [ $# = 0 ]; then
	wallp=$(/usr/bin/find "$HOME"/storage/walls/abstract -type f | shuf -n 1)
else
	wallp="$1"
fi
/usr/bin/xwallpaper --zoom "$wallp" && echo "$wallp" > ~/.cache/wallpaper && gm convert -filter Gaussian -blur 10x10 "$wallp" "$HOME/.cache/lockscreen.png"
