#!/bin/bash

active_name=$(xprop -id "$(xprop -root -f _NET_ACTIVE_WINDOW 0x " \$0\\n" _NET_ACTIVE_WINDOW|awk "{print \$2}")" WM_NAME|awk '{print $NF}')
active_clas=$(xprop -id "$(xprop -root -f _NET_ACTIVE_WINDOW 0x " \$0\\n" _NET_ACTIVE_WINDOW|awk "{print \$2}")" WM_CLASS|cut -d '"' -f4)

if [ "$active_name" = 'VIM_SERVER"' ]; then
 	vim --servername 'VIM_SERVER' --remote-send "<Esc>:wa<CR>"
        sleep 0.1
elif [ "$active_clas" = "tabbed" ]; then
        pkill tabbed
	rm $HOME/.cache/tabbed_id
fi
