#!/bin/bash

device=$(lsblk -pnr -o NAME,MOUNTPOINT | dmenu | cut -d " " -f1)
[ -s $device ] && exit
udisksctl mount -b $device
location=$(lsblk -pn -o NAME,MOUNTPOINT | grep $device | cut -d " " -f2- | tr -d '\n' | xargs)
echo "$location"
pcmanfm "$location"
