#!/bin/bash

url_regex='(https?|ftp|file)://[-[:alnum:]\+&@#/%?=~_|!:,.;]*[-[:alnum:]\+&@#/%=~_|]'
for filepath in "$@"; do
	if ! [ -f "$filepath" ] && ! [ -d "$filepath" ]; then
		if [[ $filepath =~ $url_regex ]]; then
			$BROWSER "$filepath"
		else
			continue
		fi
	elif [[ $(file --mime-type "$filepath" -b) = inode/directory ]]; then
		vifm --server-name $(vifm --server-list | head -n 1) --remote -c ":tabnew $filepath"
	elif [[ $(file --mime-type "$filepath" -b) = *pdf ]] || [[ $(file --mime-type "$filepath" -b) = *djvu ]]; then
		evince "$filepath" &>/dev/null & disown
	elif [[ $(file --mime-type "$filepath" -b) = video/* ]]; then
		mpv --volume=130 --osd-blur=10 --no-terminal --player-operation-mode=pseudo-gui --fs --no-osd-bar --save-position-on-quit "$filepath" &>/dev/null & disown
	elif [[ $(file --mime-type "$filepath" -b) = *pdf || $(file --mime-type "$filepath" -b) = *djvu ]]; then
		inkview "$filepath" &>/dev/null & disown

	elif [[ $(file --mime-type "$filepath" -b) = image/* ]]; then
		imv "$filepath" &>/dev/null & disown

	elif [[ $(file --mime-type "$filepath" -b) = audio/* ]]; then
		lollypop "$filepath" &>/dev/null & disown

	elif [[ "$filepath" == @(*.iso|*.jar|*.msi|*.pkg|*.rar|*.shar|*.tar|*.tgz|*.xar|*.xpi|*.xz|*.zip|*.7z|*.ace|*.ar|*.arc|*.bz2?|*.cab|*.cpio|*.cpt|*.deb|*.dgc|*.dmg|*.gz|*.tar.xz|*.tar.gz|*.tar.bz2) ]]; then
		echo "Extract $filepath?" | dmenu
		[ "$?" = 0 ] && xarchiver -ed "$filepath" & disown
	else
		if [ $(pgrep neovide) ]; then
			nvim --server /tmp/nvimsocket --remote-tab-silent "$filepath"
			wmctrl -xa neovide
		else
			NVIM_LISTEN_ADDRESS=/tmp/nvimsocket neovide "$filepath"
		fi
	fi
done
