#!/bin/bash

open()
{
	file=$(cat $files | dmenu) 
	echo "$file"
	[ -f "$file" ] && evince "$file" & disown

}

regen()
{
	find ~ -type f ! -path "$HOME/.cache/*" ! -path "$HOME/*conda*" ! -path "*/Trash/*" -iname "*.pdf" -o -iname "*.djvu" > "$files"
}

files="$XDG_CACHE_HOME/booklist"
if [[ "$#" == 0 ]]; then
	if [ -s "$files" ]; then
		open
		regen
	else
		regen
		open
	fi
else
	evince "$@" & disown
fi
