#!/bin/bash

open()
{
	file=$(cat $files | dmenu) 
	[ -f "$file" ] && evince "$file" & disown

}

regen()
{
	find ~/storage/books-and-papers -type f > "$files"
	find ~/storage/research-projects -type f >> "$files"
}

files="$XDG_CACHE_HOME/booklist"
if [[ "$#" == 0 ]]; then
	if [ -s "$files" ]; then
		open
		regen
	else
		regen
		open
	fi
else
	evince "$@" & disown
fi
