#!/bin/bash
if [ $# -eq 0 ]; then
    if ! wmctrl -xa 'editor'; then
	$TERMINAL --class "editor" -- bash -c "vim --servername VIM_SERVER" &
    fi
else 
    if wmctrl -xa 'editor'; then
	vim --servername VIM_SERVER --remote-tab "$@"
    else
	$TERMINAL --class "editor" -- bash -c "vim  --servername VIM_SERVER --remote-tab-silent \"$@\"" &
    fi
fi
