#!/bin/bash

volume_show()
{
	msgid=31412
	vol=$(amixer get Master | tail -n 1 | awk '{print $3}') 
	status=$(amixer get Master | tail -n 1 | awk '{print $6}') 
	icons=('🔇' '🔈' '🔉' '🔊' '🔔')
	if [ $status = '[off]' ]; then
		icon=${icons[0]}
		dunstify   -t 1000 -r ${msgid} "$icon Volume $(( $vol*100/87 ))%"
	elif [ $vol = '0' ]; then
		icon=${icons[0]}
		dunstify  -u critical -t 1000 -r ${msgid} "$icon Volume $(( $vol*100/87 ))%"
	elif [ $vol = '87' ]; then
		icon=${icons[4]}
		dunstify  -u critical -t 1000 -r ${msgid} "$icon Volume $(( $vol*100/87 ))%"
	else
		icon=${icons[$(( $vol/29 + 1))]}
		dunstify  -t 1000 -r ${msgid} "$icon Volume $(( $vol*100/87 ))%"
	fi
}


vol=$(amixer get Master | tail -n 1 | awk '{print $3}') 
case $1 in
	'-i') 	if [ $vol = '87' ]; then
			volume_show $vol
			exit
		fi
		amixer set Master unmute
		amixer set Master $2db+
		volume_show
		;;
	'-d') 	if [ $vol = '0' ]; then
			volume_show $vol
			exit
		fi
		amixer set Master unmute
		amixer set Master $2db-
		volume_show
		;;
	'-t')	amixer set Master toggle
		volume_show > ~/testfile
		;;
	*) 	volume_show ;;
esac
